# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import subprocess
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow,QFileDialog
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Graphicalprocessmodel = QtWidgets.QLabel(self.centralwidget)
        self.Graphicalprocessmodel.setGeometry(QtCore.QRect(20, 0, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Graphicalprocessmodel.setFont(font)
        self.Graphicalprocessmodel.setObjectName("Graphicalprocessmodel")
        self.Import = QtWidgets.QPushButton(self.centralwidget)
        self.Import.setGeometry(QtCore.QRect(10, 30, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Import.setFont(font)
        self.Import.setObjectName("Import")
        self.Import.clicked.connect(self.load_file)
        self.filetext = QtWidgets.QTextEdit(self.centralwidget)
        self.filetext.setGeometry(QtCore.QRect(70, 30, 201, 16))
        self.filetext.setObjectName("filetext")
        self.xmlfile = QtWidgets.QTextEdit(self.centralwidget)
        self.xmlfile.setGeometry(QtCore.QRect(10, 60, 261, 351))
        self.xmlfile.setObjectName("xmlfile")
        self.Graphicalprocessmodel_2 = QtWidgets.QLabel(self.centralwidget)
        self.Graphicalprocessmodel_2.setGeometry(QtCore.QRect(520, 0, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Graphicalprocessmodel_2.setFont(font)
        self.Graphicalprocessmodel_2.setObjectName("Graphicalprocessmodel_2")
        self.contractcode = QtWidgets.QTextEdit(self.centralwidget)
        self.contractcode.setGeometry(QtCore.QRect(380, 30, 371, 501))
        self.contractcode.setObjectName("contractcode")
        self.translate2 = QtWidgets.QPushButton(self.centralwidget)
        self.translate2.setGeometry(QtCore.QRect(280, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.translate2.setFont(font)
        self.translate2.setObjectName("translate2")
        self.translate2.clicked.connect(self.run_main_script)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionfile = QtWidgets.QAction(MainWindow)
        self.actionfile.setObjectName("actionfile")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def load_file(self):
        file_dialog = QFileDialog()
        file_dialog.setNameFilter("XML or EPML Files (*.xml *.epml)")
        file_path, _ = file_dialog.getOpenFileName(None, "Select File")
        if file_path:
            self.filetext.setText(file_path)
            with open(file_path, 'r') as file:
                content = file.read()
                self.xmlfile.setText(content)

    def run_main_script(self):
        file_content = self.filetext.toPlainText()
        script_path = "E:\python\Python\epc-to-solidity\epc-to-solidity\main.py"  # main.py 文件的路径
        result = subprocess.run(["python", script_path, file_content], capture_output=True, text=True).stdout
        self.contractcode.setPlainText(result)
        # print(result)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Graphicalprocessmodel.setText(_translate("MainWindow", "Graphical process model"))
        self.Import.setText(_translate("MainWindow", "Import"))
        self.Graphicalprocessmodel_2.setText(_translate("MainWindow", "Smart contract codes"))
        self.translate2.setText(_translate("MainWindow", "translate"))
        self.actionfile.setText(_translate("MainWindow", "file"))
if __name__ == '__main__':
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QApplication(sys.argv)
    MainWindow1 = QMainWindow()     #MainWindow1随便改
    ui = Ui_MainWindow()             #随便改
    ui.setupUi(MainWindow1)
   # MainWindow1.showMaximized()
    MainWindow1.show()
    sys.exit(app.exec_())